restore php5.6 5.5

diff --git a/Dockerfile-5.5 b/Dockerfile-5.5
--- a/Dockerfile-5.5
+++ b/Dockerfile-5.5
@@ -1,18 +1,155 @@
+FROM debian:10-slim
 
-#(nop) CMD ["php-fpm"]
-#(nop) EXPOSE 9000/tcp
-set -ex  && cd /usr/local/etc  && if [ -d php-fpm.d ]; then   sed 's!=NONE/!=!g' php-fpm.conf.default | tee php-fpm.conf > /dev/null;   cp php-fpm.d/www.conf.default php-fpm.d/www.conf;  else   mkdir php-fpm.d;   cp php-fpm.conf.default php-fpm.d/www.conf;   {    echo '[global]';    echo 'include=etc/php-fpm.d/*.conf';   } | tee php-fpm.conf;  fi  && {   echo '[global]';   echo 'error_log = /proc/self/fd/2';   echo;   echo '[www]';   echo '; if we send this to /proc/self/fd/1, it never appears';   echo 'access.log = /proc/self/fd/2';   echo;   echo 'clear_env = no';   echo;   echo '; Ensure worker stdout and stderr are sent to the main error log.';   echo 'catch_workers_output = yes';  } | tee php-fpm.d/docker.conf  && {   echo '[global]';   echo 'daemonize = no';   echo;   echo '[www]';   echo 'listen = [::]:9000';  } | tee php-fpm.d/zz-docker.conf
-#(nop) WORKDIR /var/www/html
-#(nop) COPY multi:ed54b4fe7bef284934703fa6e979b7cc0daed0549a07586d0c1ccd4e2b41884a in /usr/local/bin/
-set -xe  && buildDeps="   $PHP_EXTRA_BUILD_DEPS   libcurl4-openssl-dev   libedit-dev   libsqlite3-dev   libssl-dev   libxml2-dev  "  && apt-get update && apt-get install -y $buildDeps --no-install-recommends && rm -rf /var/lib/apt/lists/*   && docker-php-source extract  && cd /usr/src/php  && ./configure   --with-config-file-path="$PHP_INI_DIR"   --with-config-file-scan-dir="$PHP_INI_DIR/conf.d"     --disable-cgi     --enable-ftp   --enable-mbstring   --enable-mysqlnd     --with-curl   --with-libedit   --with-openssl   --with-zlib     $PHP_EXTRA_CONFIGURE_ARGS  && make -j"$(nproc)"  && make install  && { find /usr/local/bin /usr/local/sbin -type f -executable -exec strip --strip-all '{}' + || true; }  && make clean  && docker-php-source delete   && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false $buildDeps
-#(nop) COPY file:207c686e3fed4f71f8a7b245d8dcae9c9048d276a326d82b553c12a90af0c0ca in /usr/local/bin/
-set -xe  && cd /usr/src  && curl -fSL "http://php.net/get/$PHP_FILENAME/from/this/mirror" -o php.tar.xz  && echo "$PHP_SHA256 *php.tar.xz" | sha256sum -c -  && curl -fSL "http://php.net/get/$PHP_FILENAME.asc/from/this/mirror" -o php.tar.xz.asc  && export GNUPGHOME="$(mktemp -d)"  && for key in $GPG_KEYS; do   gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key";  done  && gpg --batch --verify php.tar.xz.asc php.tar.xz  && rm -r "$GNUPGHOME"
-#(nop) ENV PHP_SHA256=cb527c44b48343c8557fe2446464ff1d4695155a95601083e5d1f175df95580f
-#(nop) ENV PHP_FILENAME=php-5.5.38.tar.xz
-#(nop) ENV PHP_VERSION=5.5.38
-#(nop) ENV GPG_KEYS=0B96609E270F565C13292B24C13C70B87267B52D 0BD78B5F97500D450838F95DFE857D9A90D90EC1 F38252826ACD957EF380D39F2F7956BC5DA04B5D
-#(nop) ENV PHP_EXTRA_CONFIGURE_ARGS=--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data
-mkdir -p $PHP_INI_DIR/conf.d
-#(nop) ENV PHP_INI_DIR=/usr/local/etc/php
-apt-get update && apt-get install -y   $PHPIZE_DEPS   ca-certificates   curl   libedit2   libsqlite3-0   libxml2   xz-utils  --no-install-recommends && rm -r /var/lib/apt/lists/*
-#(nop) ENV PHPIZE_DEPS=autoconf   file   g++   gcc   libc-dev   make   pkg-config   re2c
+ARG s6url=https://github.com/just-containers/s6-overlay/releases/download/v1.22.1.0/s6-overlay-amd64.tar.gz
+ARG php_url=https://www.php.net/get/php-7.2.24.tar.xz/from/this/mirror
+
+# prevent Debian's PHP packages from being installed
+# https://github.com/docker-library/php/pull/542
+RUN set -eux; \
+	{ \
+		echo 'Package: php*'; \
+		echo 'Pin: release *'; \
+		echo 'Pin-Priority: -1'; \
+	} > /etc/apt/preferences.d/no-debian-php
+
+ENV PHPIZE_DEPS \
+        autoconf \
+        dpkg-dev \
+        file \
+        g++ \
+        gcc \
+        libc-dev \
+        make \
+        pkg-config \
+        re2c \
+        vim
+
+RUN set -eux \
+  ;sed -i 's/\(.*\)\(security\|deb\).debian.org\(.*\)main/\1ftp2.cn.debian.org\3main contrib non-free/g' /etc/apt/sources.list \
+  ; apt-get update \
+  ; apt-get install -y --no-install-recommends \
+        apt-transport-https \
+        ca-certificates \
+        curl \
+        libedit2 \
+        libsqlite3-0 \
+        libxml2 \
+        xz-utils\
+        $PHPIZE_DEPS \
+  ; apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*
+
+ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 TIMEZONE=Asia/Shanghai
+RUN set -eux \
+  ; ln -sf /usr/share/zoneinfo/$TIMEZONE /etc/localtime \
+  ; echo "$TIMEZONE" > /etc/timezone
+
+ENV PHP_INI_DIR=/usr/local/etc/php
+RUN set -eux; \
+	mkdir -p "$PHP_INI_DIR/conf.d"; \
+# allow running as an arbitrary user (https://github.com/docker-library/php/issues/743)
+	chown www-data:www-data /srv; \
+	chmod 777 /srv
+
+ENV PHP_EXTRA_CONFIGURE_ARGS \
+        --enable-fpm \
+        --with-fpm-user=www-data \
+        --with-fpm-group=www-data
+
+ENV GPG_KEYS 0B96609E270F565C13292B24C13C70B87267B52D 0BD78B5F97500D450838F95DFE857D9A90D90EC1 F38252826ACD957EF380D39F2F7956BC5DA04B5D
+
+ENV PHP_VERSION=5.5.38
+ENV PHP_FILENAME=php-5.5.38.tar.xz
+ENV PHP_SHA256=cb527c44b48343c8557fe2446464ff1d4695155a95601083e5d1f175df95580f
+
+RUN set -xue  \
+  ; cd /usr/src \
+  ; curl -fSL "http://php.net/get/$PHP_FILENAME/from/this/mirror" -o php.tar.xz  \
+  ; echo "$PHP_SHA256 *php.tar.xz" | sha256sum -c -  \
+  ; curl -fSL "http://php.net/get/$PHP_FILENAME.asc/from/this/mirror" -o php.tar.xz.asc  \
+  ; export GNUPGHOME="$(mktemp -d)"  \
+  ; for key in $GPG_KEYS; do \
+        gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
+    done \
+  ; gpg --batch --verify php.tar.xz.asc php.tar.xz  \
+  ; rm -r "$GNUPGHOME"
+
+COPY docker-php-source /usr/local/bin/
+
+RUN set -eux \
+  ; buildDeps="\
+        $PHP_EXTRA_BUILD_DEPS \
+        libcurl4-openssl-dev \
+        libedit-dev \
+        libsqlite3-dev \
+        libssl-dev \
+        libxml2-dev"  \
+  ; apt-get update \
+  ; apt-get install -y $buildDeps --no-install-recommends \
+  ; rm -rf /var/lib/apt/lists/*   \
+  ; docker-php-source extract  \
+  ; cd /usr/src/php  \
+  ; ./configure \
+        --with-config-file-path="$PHP_INI_DIR" \
+        --with-config-file-scan-dir="$PHP_INI_DIR/conf.d" \
+        --disable-cgi  \
+        --enable-ftp \
+        --enable-mbstring \
+        --enable-mysqlnd \
+        --with-curl \
+        --with-libedit \
+        --with-openssl \
+        --with-zlib  \
+        $PHP_EXTRA_CONFIGURE_ARGS \
+  ; make -j"$(nproc)"  \
+  ; make install  \
+  ; { find /usr/local/bin /usr/local/sbin -type f -executable -exec strip --strip-all '{}' + || true; }  \
+  ; make clean  \
+  ; docker-php-source delete \
+  ; apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false $buildDeps
+
+COPY docker-php-ext-* docker-php-entrypoint /usr/local/bin/
+
+
+RUN set -ex  \
+  ; cd /usr/local/etc \
+  ; if [ -d php-fpm.d ]; then \
+        sed 's!=NONE/!=!g' php-fpm.conf.default \
+            | tee php-fpm.conf > /dev/null; \
+        cp php-fpm.d/www.conf.default php-fpm.d/www.conf; \
+    else \
+        mkdir php-fpm.d; \
+        cp php-fpm.conf.default php-fpm.d/www.conf; \
+        {    echo '[global]';    echo 'include=etc/php-fpm.d/*.conf';   } \
+            | tee php-fpm.conf; \
+    fi \
+  ; { \
+        echo '[global]'; \
+        echo 'error_log = /proc/self/fd/2'; \
+        echo; \
+        echo '[www]'; \
+        echo '; if we send this to /proc/self/fd/1, it never appears'; \
+        echo 'access.log = /proc/self/fd/2'; \
+        echo; \
+        echo 'clear_env = no'; \
+        echo; \
+        echo '; Ensure worker stdout and stderr are sent to the main error log.'; \
+        echo 'catch_workers_output = yes'; \
+    } | tee php-fpm.d/docker.conf  \
+  ; { \
+        echo '[global]'; \
+        echo 'daemonize = no'; \
+        echo; \
+        echo '[www]'; \
+        echo 'listen = [::]:9000'; \
+    } | tee php-fpm.d/zz-docker.conf
+
+WORKDIR /srv
+
+VOLUME [ "/srv", "/root/.vscode-server" ]
+EXPOSE 80
+
+ENTRYPOINT [ "/init" ]
+
+
+
+
diff --git a/Dockerfile-5.6 b/Dockerfile-5.6
--- a/Dockerfile-5.6
+++ b/Dockerfile-5.6
@@ -1,24 +1,90 @@
-#(nop)  CMD ["php-fpm"]
-#(nop)  EXPOSE 9000
-set -ex  && cd /usr/local/etc  && if [ -d php-fpm.d ]; then   sed 's!=NONE/!=!g' php-fpm.conf.default | tee php-fpm.conf > /dev/null;   cp php-fpm.d/www.conf.default php-fpm.d/www.conf;  else   mkdir php-fpm.d;   cp php-fpm.conf.default php-fpm.d/www.conf;   {    echo '[global]';    echo 'include=etc/php-fpm.d/*.conf';   } | tee php-fpm.conf;  fi  && {   echo '[global]';   echo 'error_log = /proc/self/fd/2';   echo;   echo '[www]';   echo '; if we send this to /proc/self/fd/1, it never appears';   echo 'access.log = /proc/self/fd/2';   echo;   echo 'clear_env = no';   echo;   echo '; Ensure worker stdout and stderr are sent to the main error log.';   echo 'catch_workers_output = yes';  } | tee php-fpm.d/docker.conf  && {   echo '[global]';   echo 'daemonize = no';   echo;   echo '[www]';   echo 'listen = 9000';  } | tee php-fpm.d/zz-docker.conf
-#(nop) WORKDIR /var/www/html
-#(nop)  ENTRYPOINT ["docker-php-entrypoint"]
-#(nop) COPY multi:cbc68fef2c8554b9a23fee7eee16ffda927235f929048638240f97172562665c in /usr/local/bin/
-set -eux;   savedAptMark="$(apt-mark showmanual)";  apt-get update;  apt-get install -y --no-install-recommends   libcurl4-openssl-dev   libedit-dev   libsqlite3-dev   libssl1.0-dev   libxml2-dev   zlib1g-dev   ${PHP_EXTRA_BUILD_DEPS:-}  ;  rm -rf /var/lib/apt/lists/*;   export   CFLAGS="$PHP_CFLAGS"   CPPFLAGS="$PHP_CPPFLAGS"   LDFLAGS="$PHP_LDFLAGS"  ;  docker-php-source extract;  cd /usr/src/php;  gnuArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)";  debMultiarch="$(dpkg-architecture --query DEB_BUILD_MULTIARCH)";  if [ ! -d /usr/include/curl ]; then   ln -sT "/usr/include/$debMultiarch/curl" /usr/local/include/curl;  fi;  ./configure   --build="$gnuArch"   --with-config-file-path="$PHP_INI_DIR"   --with-config-file-scan-dir="$PHP_INI_DIR/conf.d"     --enable-option-checking=fatal     --with-mhash     --enable-ftp   --enable-mbstring   --enable-mysqlnd     --with-curl   --with-libedit   --with-openssl   --with-zlib     $(test "$gnuArch" = 's390x-linux-gnu' && echo '--without-pcre-jit')   --with-libdir="lib/$debMultiarch"     ${PHP_EXTRA_CONFIGURE_ARGS:-}  ;  make -j "$(nproc)";  make install;  find /usr/local/bin /usr/local/sbin -type f -executable -exec strip --strip-all '{}' + || true;  make clean;   cp -v php.ini-* "$PHP_INI_DIR/";   cd /;  docker-php-source delete;   apt-mark auto '.*' > /dev/null;  [ -z "$savedAptMark" ] || apt-mark manual $savedAptMark;  find /usr/local -type f -executable -exec ldd '{}' ';'   | awk '/=>/ { print $(NF-1) }'   | sort -u   | xargs -r dpkg-query --search   | cut -d: -f1   | sort -u   | xargs -r apt-mark manual  ;  apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false;   php --version;   pecl update-channels;  rm -rf /tmp/pear ~/.pearrc
-#(nop) COPY file:ce57c04b70896f77cc11eb2766417d8a1240fcffe5bba92179ec78c458844110 in /usr/local/bin/
+FROM debian:10-slim
+
+ARG s6url=https://github.com/just-containers/s6-overlay/releases/download/v1.22.1.0/s6-overlay-amd64.tar.gz
+ARG php_url=https://www.php.net/get/php-7.2.24.tar.xz/from/this/mirror
+
+# prevent Debian's PHP packages from being installed
+# https://github.com/docker-library/php/pull/542
+RUN set -eux; \
+	{ \
+		echo 'Package: php*'; \
+		echo 'Pin: release *'; \
+		echo 'Pin-Priority: -1'; \
+	} > /etc/apt/preferences.d/no-debian-php
+
+ENV PHPIZE_DEPS \
+        autoconf \
+        dpkg-dev \
+        file \
+        g++ \
+        gcc \
+        libc-dev \
+        make \
+        pkg-config \
+        re2c \
+        vim
+
+RUN set -eux \
+  ;sed -i 's/\(.*\)\(security\|deb\).debian.org\(.*\)main/\1ftp2.cn.debian.org\3main contrib non-free/g' /etc/apt/sources.list \
+  ; apt-get update \
+  ; apt-get install -y --no-install-recommends \
+        apt-transport-https \
+        ca-certificates \
+        curl \
+        libedit2 \
+        libsqlite3-0 \
+        libxml2 \
+        xz-utils\
+        $PHPIZE_DEPS \
+  ; apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*
+
+ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 TIMEZONE=Asia/Shanghai
+RUN set -eux \
+  ; ln -sf /usr/share/zoneinfo/$TIMEZONE /etc/localtime \
+  ; echo "$TIMEZONE" > /etc/timezone
+
+ENV PHP_INI_DIR=/usr/local/etc/php
+RUN set -eux; \
+	mkdir -p "$PHP_INI_DIR/conf.d"; \
+# allow running as an arbitrary user (https://github.com/docker-library/php/issues/743)
+	chown www-data:www-data /srv; \
+	chmod 777 /srv
+
+ENV PHP_EXTRA_CONFIGURE_ARGS \
+        --enable-fpm \
+        --with-fpm-user=www-data \
+        --with-fpm-group=www-data \
+        --disable-cgi
+
+ENV PHP_CFLAGS \
+        -fstack-protector-strong \
+        -fpic \
+        -fpie \
+        -O2
+
+ENV PHP_CPPFLAGS \
+        -fstack-protector-strong \
+        -fpic \
+        -fpie \
+        -O2
+
+ENV PHP_LDFLAGS \
+        -Wl,-O1 \
+        -Wl,--hash-style=both \
+        -pie
+
+ENV GPG_KEYS 0BD78B5F97500D450838F95DFE857D9A90D90EC1 6E4F6AB321FDC07F2C332E3AC2BF0BC433CFC8B3
+ENV PHP_VERSION=5.6.40
+ENV PHP_URL=https://secure.php.net/get/php-5.6.40.tar.xz/from/this/mirror
+ENV PHP_ASC_URL=https://secure.php.net/get/php-5.6.40.tar.xz.asc/from/this/mirror
+ENV PHP_SHA256=1369a51eee3995d7fbd1c5342e5cc917760e276d561595b6052b21ace2656d1c PHP_MD5=
+
 set -xe;   fetchDeps='   wget  ';  if ! command -v gpg > /dev/null; then   fetchDeps="$fetchDeps    dirmngr    gnupg   ";  fi;  apt-get update;  apt-get install -y --no-install-recommends $fetchDeps;  rm -rf /var/lib/apt/lists/*;   mkdir -p /usr/src;  cd /usr/src;   wget -O php.tar.xz "$PHP_URL";   if [ -n "$PHP_SHA256" ]; then   echo "$PHP_SHA256 *php.tar.xz" | sha256sum -c -;  fi;  if [ -n "$PHP_MD5" ]; then   echo "$PHP_MD5 *php.tar.xz" | md5sum -c -;  fi;   if [ -n "$PHP_ASC_URL" ]; then   wget -O php.tar.xz.asc "$PHP_ASC_URL";   export GNUPGHOME="$(mktemp -d)";   for key in $GPG_KEYS; do    gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys "$key";   done;   gpg --batch --verify php.tar.xz.asc php.tar.xz;   command -v gpgconf > /dev/null && gpgconf --kill all;   rm -rf "$GNUPGHOME";  fi;   apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false $fetchDeps
-#(nop)  ENV PHP_SHA256=1369a51eee3995d7fbd1c5342e5cc917760e276d561595b6052b21ace2656d1c PHP_MD5=
-#(nop)  ENV PHP_URL=https://secure.php.net/get/php-5.6.40.tar.xz/from/this/mirror PHP_ASC_URL=https://secure.php.net/get/php-5.6.40.tar.xz.asc/from/this/mirror
-#(nop)  ENV PHP_VERSION=5.6.40
-#(nop)  ENV GPG_KEYS=0BD78B5F97500D450838F95DFE857D9A90D90EC1 6E4F6AB321FDC07F2C332E3AC2BF0BC433CFC8B3
-#(nop)  ENV PHP_LDFLAGS=-Wl,-O1 -Wl,--hash-style=both -pie
-#(nop)  ENV PHP_CPPFLAGS=-fstack-protector-strong -fpic -fpie -O2
-#(nop)  ENV PHP_CFLAGS=-fstack-protector-strong -fpic -fpie -O2
-#(nop)  ENV PHP_EXTRA_CONFIGURE_ARGS=--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi
-mkdir -p $PHP_INI_DIR/conf.d
-#(nop)  ENV PHP_INI_DIR=/usr/local/etc/php
-apt-get update && apt-get install -y   $PHPIZE_DEPS   ca-certificates   curl   xz-utils  --no-install-recommends && rm -r /var/lib/apt/lists/*
-#(nop)  ENV PHPIZE_DEPS=autoconf   dpkg-dev   file   g++   gcc   libc-dev   make   pkg-config   re2c
-set -eux;  {   echo 'Package: php*';   echo 'Pin: release *';   echo 'Pin-Priority: -1';  } > /etc/apt/preferences.d/no-debian-php
-#(nop)  CMD ["bash"]
-#(nop) ADD file:a65337a57a064a79ad8a3f42e8282b3e01710cb4684ccd880463cc8d2e051fa5 in /
+#(nop) COPY file:ce57c04b70896f77cc11eb2766417d8a1240fcffe5bba92179ec78c458844110 in /usr/local/bin/
+set -eux;   savedAptMark="$(apt-mark showmanual)";  apt-get update;  apt-get install -y --no-install-recommends   libcurl4-openssl-dev   libedit-dev   libsqlite3-dev   libssl1.0-dev   libxml2-dev   zlib1g-dev   ${PHP_EXTRA_BUILD_DEPS:-}  ;  rm -rf /var/lib/apt/lists/*;   export   CFLAGS="$PHP_CFLAGS"   CPPFLAGS="$PHP_CPPFLAGS"   LDFLAGS="$PHP_LDFLAGS"  ;  docker-php-source extract;  cd /usr/src/php;  gnuArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)";  debMultiarch="$(dpkg-architecture --query DEB_BUILD_MULTIARCH)";  if [ ! -d /usr/include/curl ]; then   ln -sT "/usr/include/$debMultiarch/curl" /usr/local/include/curl;  fi;  ./configure   --build="$gnuArch"   --with-config-file-path="$PHP_INI_DIR"   --with-config-file-scan-dir="$PHP_INI_DIR/conf.d"     --enable-option-checking=fatal     --with-mhash     --enable-ftp   --enable-mbstring   --enable-mysqlnd     --with-curl   --with-libedit   --with-openssl   --with-zlib     $(test "$gnuArch" = 's390x-linux-gnu' && echo '--without-pcre-jit')   --with-libdir="lib/$debMultiarch"     ${PHP_EXTRA_CONFIGURE_ARGS:-}  ;  make -j "$(nproc)";  make install;  find /usr/local/bin /usr/local/sbin -type f -executable -exec strip --strip-all '{}' + || true;  make clean;   cp -v php.ini-* "$PHP_INI_DIR/";   cd /;  docker-php-source delete;   apt-mark auto '.*' > /dev/null;  [ -z "$savedAptMark" ] || apt-mark manual $savedAptMark;  find /usr/local -type f -executable -exec ldd '{}' ';'   | awk '/=>/ { print $(NF-1) }'   | sort -u   | xargs -r dpkg-query --search   | cut -d: -f1   | sort -u   | xargs -r apt-mark manual  ;  apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false;   php --version;   pecl update-channels;  rm -rf /tmp/pear ~/.pearrc
+#(nop) COPY multi:cbc68fef2c8554b9a23fee7eee16ffda927235f929048638240f97172562665c in /usr/local/bin/
+#(nop)  ENTRYPOINT ["docker-php-entrypoint"]
+#(nop) WORKDIR /var/www/html
+set -ex  && cd /usr/local/etc  && if [ -d php-fpm.d ]; then   sed 's!=NONE/!=!g' php-fpm.conf.default | tee php-fpm.conf > /dev/null;   cp php-fpm.d/www.conf.default php-fpm.d/www.conf;  else   mkdir php-fpm.d;   cp php-fpm.conf.default php-fpm.d/www.conf;   {    echo '[global]';    echo 'include=etc/php-fpm.d/*.conf';   } | tee php-fpm.conf;  fi  && {   echo '[global]';   echo 'error_log = /proc/self/fd/2';   echo;   echo '[www]';   echo '; if we send this to /proc/self/fd/1, it never appears';   echo 'access.log = /proc/self/fd/2';   echo;   echo 'clear_env = no';   echo;   echo '; Ensure worker stdout and stderr are sent to the main error log.';   echo 'catch_workers_output = yes';  } | tee php-fpm.d/docker.conf  && {   echo '[global]';   echo 'daemonize = no';   echo;   echo '[www]';   echo 'listen = 9000';  } | tee php-fpm.d/zz-docker.conf
+#(nop)  EXPOSE 9000
+#(nop)  CMD ["php-fpm"]
