docker history

diff --git a/Dockerfile-5.6 b/Dockerfile-5.6
--- a/Dockerfile-5.6
+++ b/Dockerfile-5.6
@@ -1,31 +1,24 @@
-FROM php:5.6-fpm-alpine
-
-# sodium was built as a shared module (so that it can be replaced later if so desired), so let's enable it too (https://github.com/docker-library/php/issues/598)
-RUN docker-php-ext-enable sodium
-
-# temporary "freetype-config" workaround for https://github.com/docker-library/php/issues/865 (https://bugs.php.net/bug.php?id=76324)
-RUN { echo '#!/bin/sh'; echo 'exec pkg-config "$@" freetype2'; } > /usr/local/bin/freetype-config && chmod +x /usr/local/bin/freetype-config
-
-RUN apk add --no-cache \
-        libfreetype6-dev \
-        libjpeg62-turbo-dev \
-        libpng-dev \
-    && docker-php-ext-install -j$(nproc) iconv \
-    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
-    && docker-php-ext-install -j$(nproc) gd \
-	&& rm -rf /var/lib/apt/lists/*
-
-RUN set -eux \
-  ; pecl install redis-4.0.1 \
-  ; pecl install xdebug-2.6.0 \
-  ; docker-php-ext-enable redis xdebug \
-  ; docker-php-ext-install mysqli && docker-php-ext-enable mysqli \
-  ; docker-php-ext-install mysql && docker-php-ext-enable mysql \
-  ; docker-php-ext-install pdo && docker-php-ext-enable pdo \
-  ; docker-php-ext-install pdo_mysql && docker-php-ext-enable pdo_mysql \
-  #; docker-php-ext-install curl && docker-php-ext-enable curl \
-  #; docker-php-ext-install bz2 && docker-php-ext-enable bz2 \
-  ; docker-php-ext-install mbstring && docker-php-ext-enable mbstring \
-  ; docker-php-ext-install bcmath && docker-php-ext-enable bcmath \
-  ; docker-php-ext-install zip && docker-php-ext-enable zip
-
+#(nop)  CMD ["php-fpm"]
+#(nop)  EXPOSE 9000
+set -ex  && cd /usr/local/etc  && if [ -d php-fpm.d ]; then   sed 's!=NONE/!=!g' php-fpm.conf.default | tee php-fpm.conf > /dev/null;   cp php-fpm.d/www.conf.default php-fpm.d/www.conf;  else   mkdir php-fpm.d;   cp php-fpm.conf.default php-fpm.d/www.conf;   {    echo '[global]';    echo 'include=etc/php-fpm.d/*.conf';   } | tee php-fpm.conf;  fi  && {   echo '[global]';   echo 'error_log = /proc/self/fd/2';   echo;   echo '[www]';   echo '; if we send this to /proc/self/fd/1, it never appears';   echo 'access.log = /proc/self/fd/2';   echo;   echo 'clear_env = no';   echo;   echo '; Ensure worker stdout and stderr are sent to the main error log.';   echo 'catch_workers_output = yes';  } | tee php-fpm.d/docker.conf  && {   echo '[global]';   echo 'daemonize = no';   echo;   echo '[www]';   echo 'listen = 9000';  } | tee php-fpm.d/zz-docker.conf
+#(nop) WORKDIR /var/www/html
+#(nop)  ENTRYPOINT ["docker-php-entrypoint"]
+#(nop) COPY multi:cbc68fef2c8554b9a23fee7eee16ffda927235f929048638240f97172562665c in /usr/local/bin/
+set -eux;   savedAptMark="$(apt-mark showmanual)";  apt-get update;  apt-get install -y --no-install-recommends   libcurl4-openssl-dev   libedit-dev   libsqlite3-dev   libssl1.0-dev   libxml2-dev   zlib1g-dev   ${PHP_EXTRA_BUILD_DEPS:-}  ;  rm -rf /var/lib/apt/lists/*;   export   CFLAGS="$PHP_CFLAGS"   CPPFLAGS="$PHP_CPPFLAGS"   LDFLAGS="$PHP_LDFLAGS"  ;  docker-php-source extract;  cd /usr/src/php;  gnuArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)";  debMultiarch="$(dpkg-architecture --query DEB_BUILD_MULTIARCH)";  if [ ! -d /usr/include/curl ]; then   ln -sT "/usr/include/$debMultiarch/curl" /usr/local/include/curl;  fi;  ./configure   --build="$gnuArch"   --with-config-file-path="$PHP_INI_DIR"   --with-config-file-scan-dir="$PHP_INI_DIR/conf.d"     --enable-option-checking=fatal     --with-mhash     --enable-ftp   --enable-mbstring   --enable-mysqlnd     --with-curl   --with-libedit   --with-openssl   --with-zlib     $(test "$gnuArch" = 's390x-linux-gnu' && echo '--without-pcre-jit')   --with-libdir="lib/$debMultiarch"     ${PHP_EXTRA_CONFIGURE_ARGS:-}  ;  make -j "$(nproc)";  make install;  find /usr/local/bin /usr/local/sbin -type f -executable -exec strip --strip-all '{}' + || true;  make clean;   cp -v php.ini-* "$PHP_INI_DIR/";   cd /;  docker-php-source delete;   apt-mark auto '.*' > /dev/null;  [ -z "$savedAptMark" ] || apt-mark manual $savedAptMark;  find /usr/local -type f -executable -exec ldd '{}' ';'   | awk '/=>/ { print $(NF-1) }'   | sort -u   | xargs -r dpkg-query --search   | cut -d: -f1   | sort -u   | xargs -r apt-mark manual  ;  apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false;   php --version;   pecl update-channels;  rm -rf /tmp/pear ~/.pearrc
+#(nop) COPY file:ce57c04b70896f77cc11eb2766417d8a1240fcffe5bba92179ec78c458844110 in /usr/local/bin/
+set -xe;   fetchDeps='   wget  ';  if ! command -v gpg > /dev/null; then   fetchDeps="$fetchDeps    dirmngr    gnupg   ";  fi;  apt-get update;  apt-get install -y --no-install-recommends $fetchDeps;  rm -rf /var/lib/apt/lists/*;   mkdir -p /usr/src;  cd /usr/src;   wget -O php.tar.xz "$PHP_URL";   if [ -n "$PHP_SHA256" ]; then   echo "$PHP_SHA256 *php.tar.xz" | sha256sum -c -;  fi;  if [ -n "$PHP_MD5" ]; then   echo "$PHP_MD5 *php.tar.xz" | md5sum -c -;  fi;   if [ -n "$PHP_ASC_URL" ]; then   wget -O php.tar.xz.asc "$PHP_ASC_URL";   export GNUPGHOME="$(mktemp -d)";   for key in $GPG_KEYS; do    gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys "$key";   done;   gpg --batch --verify php.tar.xz.asc php.tar.xz;   command -v gpgconf > /dev/null && gpgconf --kill all;   rm -rf "$GNUPGHOME";  fi;   apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false $fetchDeps
+#(nop)  ENV PHP_SHA256=1369a51eee3995d7fbd1c5342e5cc917760e276d561595b6052b21ace2656d1c PHP_MD5=
+#(nop)  ENV PHP_URL=https://secure.php.net/get/php-5.6.40.tar.xz/from/this/mirror PHP_ASC_URL=https://secure.php.net/get/php-5.6.40.tar.xz.asc/from/this/mirror
+#(nop)  ENV PHP_VERSION=5.6.40
+#(nop)  ENV GPG_KEYS=0BD78B5F97500D450838F95DFE857D9A90D90EC1 6E4F6AB321FDC07F2C332E3AC2BF0BC433CFC8B3
+#(nop)  ENV PHP_LDFLAGS=-Wl,-O1 -Wl,--hash-style=both -pie
+#(nop)  ENV PHP_CPPFLAGS=-fstack-protector-strong -fpic -fpie -O2
+#(nop)  ENV PHP_CFLAGS=-fstack-protector-strong -fpic -fpie -O2
+#(nop)  ENV PHP_EXTRA_CONFIGURE_ARGS=--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi
+mkdir -p $PHP_INI_DIR/conf.d
+#(nop)  ENV PHP_INI_DIR=/usr/local/etc/php
+apt-get update && apt-get install -y   $PHPIZE_DEPS   ca-certificates   curl   xz-utils  --no-install-recommends && rm -r /var/lib/apt/lists/*
+#(nop)  ENV PHPIZE_DEPS=autoconf   dpkg-dev   file   g++   gcc   libc-dev   make   pkg-config   re2c
+set -eux;  {   echo 'Package: php*';   echo 'Pin: release *';   echo 'Pin-Priority: -1';  } > /etc/apt/preferences.d/no-debian-php
+#(nop)  CMD ["bash"]
+#(nop) ADD file:a65337a57a064a79ad8a3f42e8282b3e01710cb4684ccd880463cc8d2e051fa5 in /
